os: linux

language: "go"

sudo: true

go:
  - 1.13.x

script:
  - export GO111MODULE=on
  - ./.travis.gofmt.sh
  - go test -v -race $(go list ./... | grep -v vendor)
  - GOOS=linux GOARCH=amd64 go build -o pm5-emulator cmd/pm5-emulator/main.go